config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :reservations, only: [:index, :create]
  end

  resources :trailers do
    resources :reservations, only: [:index, :create]
  end

  resources :reservations, only: [:show]

  resource :profiles, only: [:show]

  resources :user_trailers, only: [:index, :show]

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :trailer

  validates :start_date, :end_date, presence: true
  def info
    "<b>#{trailer.model}</b>\n
    De #{start_date.strftime("%Y/%m/%d")} a #{end_date.strftime("%Y/%m/%d")}\n
    Preço da diária: $ #{trailer.price}\n
    Endereço: #{trailer.address}"
  end
end

app/models/trailer.rb
class Trailer < ApplicationRecord
  validates :price, :model, :onboard_capacity, :description, :address, presence: true

  has_one_attached :photo
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone_number, :first_name, :last_name, presence: true
  #validates :phone_number

  has_one_attached :photo
  has_many :reservations, dependent: :destroy
  has_many :trailers
  has_many :trailers, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number])

    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @reservations_client = Reservation.where(user_id: current_user.id)
    @reservations_owner = Reservation.where(trailer_id: current_user.trailers.ids)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show edit update destroy]

  def index
    @trailer = Trailer.find(params[:trailer_id])
    @reservations = Reservation.all
  end

  # def new
  #   @trailer = Trailer.find(params[:trailer_id])
  #   @user = User.find(params[:user_id])
  #   @reservation = Reservation.new
  # end

  def show
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @trailer = Trailer.find(params[:trailer_id])
    @reservation.trailer = @trailer
    @reservation.user = current_user
    # valid_reservation = true

    # @trailer.reservations.each do |reservation|
    #   unless (reservation.start_date < @reservation.end_date || reservation.end_date > @reservation.start_date || @reservation.end_date < @reservation.start_date)
    #     valid_reservation = false
    #   end
    # end
    if @reservation.save
      redirect_to reservation_path(@reservation)
    else
      render "trailers/show", notice: "Reserva não concluída. Revise seus dados"
    end
  end

  # def edit
  # end

  # def update
  #   @reservation.update(reservation_params)
  #   redirect_to reservation_path(@reservation)
  # end

  # def destroy
  #   @reservation = reservation.find(params[:id])
  #   @user = @reservation.user
  #   @reservation.destroy
  #   redirect_to user_path(@reservation.user)
  # end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :set_trailer, only: %i[show edit update destroy]
  # before_action :validate_current_user, only: %i[edit update destroy]
  def index
    if params[:search]
      unless params[:search][:start_date].blank? &&
             params[:search][:end_date].blank? &&
             params[:search][:query].blank? &&
             params[:search][:capacity].blank?
        @reservation = Reservation.new(start_date: params[:search][:start_date], end_date: params[:search][:end_date])
        if params[:search][:capacity].blank?
          @trailers = Trailer.where("address ILIKE ?", "%#{params[:search][:query]}%")
        else
          @trailers = Trailer.where("address ILIKE ?", "%#{params[:search][:query]}%")
                             .where(onboard_capacity: params[:search][:capacity])
          @trailers.select do |trailer|
            Reservation.where(trailer: trailer).where("start_date > ? OR end_date <  ?", params[:search][:end_date], params[:search][:start_date]).empty?
          end
        end
        @markers = @trailers.geocoded.map do |flat|
          {
            lat: flat.latitude,
            lng: flat.longitude,
            infoWindow: render_to_string(partial: "info_window", locals: { trailer: @trailers })
          }
        end
      else
        @trailers = Trailer.order(created_at: :desc)
        @markers = @trailers.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { trailer: @trailers })
        }
        end
      end
    else
      @trailers = Trailer.order(created_at: :desc)
      @markers = @trailers.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { trailer: @trailers })
        }
      end
    end
  end

  def show
    @reservation = Reservation.new
  end

  def new
    @trailer = Trailer.new
  end

  def create
    @trailer = Trailer.new(trailer_params)
    @trailer.user = current_user
    if @trailer.save
      redirect_to trailer_path(@trailer)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @trailer.update(trailer_params)
    redirect_to trailer_path(@trailer)
  end

  def destroy
    @trailer.destroy
    redirect_to trailers_path
  end

  private

  def set_trailer
    @trailer = Trailer.find(params[:id])
  end

  def trailer_params
    params.require(:trailer).permit(:model, :price, :description, :address, :onboard_capacity, :photo, :start_date, :end_date)
  end

  # def validate_current_user
  #   if !current_user.admin? && @trailer.user != current_user
  #     redirect_to root_path, alert: 'Invalid action'
  #     return
  #   end
  # end
end

app/controllers/user_trailers_controller.rb
class UserTrailersController < ApplicationController
  def index
    @trailers = Trailer.where(user: current_user)
  end

  def show
    @trailer = Trailer.find(params[:id])
    @reservations = @trailer.reservations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tem Trailer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no"">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/layouts/passo-a-passo.html.erb
# 1) MODEL USER
Criou um User devise model - Somente email e password (e suas validacoes)
rails g devise User

# 2) ADICIONAMOS COLUNAS NO USER
Colunas adicionadas - Phone Number, Description, Profile Image, First Name, Last Name
rails g migration AddColumnToUser

def change
  add_column :users, :phone_number, :string
  (...)
end

# 3) VALIDAMOS A PRESENCA DOS CAMPOS DO USER
validates :phone_number, :first_name, :last_name, presence: true

# 4) POR DEFAULT DO DEVISE, O USER JA TINHA CONTROLLER EMBUTIDO. (New, Create, Edit, Update, Delete)
Criamos um controller para que o usuario acesse o show (my profile) - Controller Profile

# 5) ALTERAMOS O FORM DO 'views/devise/registrations/edit' e 'views/devise/registrations/new' E ADICIONAMOS FIRST_NAME, LAST_NAME E PHONE-NUMBER

# 6) ADICIONAMOS O STRONG PARAMS DO FIRST_NAME, LAST_NAME e PHONE NUMBER NO 'application_controller'

# 7) TRAILER MODEL
rails g model Trailer price:integer model description:text coordinates onboard_capacity:integer user:references

# 8) VALIDAMOS A PRESENCA DOS CAMPOS DO TRAILER
validates :price, :model, :onboard_capacity, :description, :address, presence: true

# 9) ASSOCIACOES DE TRAILER PARA USER - No modelo de trailer

belongs_to :user ***locador***

# 10) ASSOCIACOES DE USER PARA TRAILER - No modelo de user
has_many :trailers ***locador***

# 11) CRIAMOS AS ROTAS DO TRAILER
Utilizando resources :trailers

# 12) CRIAMOS O CONTROLLER DO TRAILER
rails g controller Trailers index show new create edit update destroy

# 13) ADICIONAMOS AS RESPECTIVAS FUNCIONALIDADES PARA OS METODOS

# 14) CRIAMOS UM METODO CHAMADO SHOW_TRAILERS QUE LISTA TODOS OS TRAILERS QUE AQUELE USUARIO TEM
  Criamos um controller chamado USER TRAILERS

  def show_trailers
    @trailers = Trailer.where(user_id: current_user)
  end

# 15) CRIAMOS UM CAMINHO PARA MOSTRAR ESSE METODO DE SHOW_TRAILERS

# 16) EDITAMOS AS RESPECTIVAS VIEWS DO TRAILER:
Index- Criei uma div com cards, os cards em si com o modelo e descricao. Tb criei os botoes com autorizacao
Show- Card com as informacoes detalhadas do trailer em si (@trailer)
New- Renderizando o formulario do form
Edit- Renderizando o formulario do form
***Criamos uma view para o metodo show_trailers*** Show_trailers- Se tiver trailer cadastrados: liste os trailers. Se nao tiver, mostre o botao para adicionar


# 17) CRIAR O MODELO DO RESERVATION
rails g model Reservation price:integer total:integer description:text rating:integer start_date:date end_date:date user:references trailer:references

# 18) VALIDAMOS AS CAMPOS NECESSARIOS DE RESERVATION
validates :start_date, :end_date, presence: true

# 19) ASSOCIACOES DE RESERVATIONS COM OS DEMAIS
belongs_to :user
belongs_to :trailer

# 20) ASSOCIACOES DE USER COM RESERVATIONS
has_many :reservations, dependent: :destroy
*** Adicionamos que agora os usuarios podem ter trailers atraves das reservas (locatario) **
has_many :trailers, through: :reservations ***locatario***

# 21) ASSOCIACOES DE TRAILER COM RESERVATIONS
has_many :reservations, dependent: :destroy
*** Adicionamos que agora os trailers podem ter usuarios atraves das reservas (locatario)***
has_many :users, through: :reservations ***locatario***


# 22) CRIAMOS ROTAS PARA AS RESERVATIONS
reservas que so podem ser acessadas atraves do usuario
  devise_for :users do
    resources :reservations, only: [:index, :create]
  end

reservas que so podem ser criadas/acessadas atraves do trailer
  resources :trailers do
    resources :reservations, only: [:index]
  end

# 23) CRIAMOS CONTROLLER PARA RESERVATIONS

# 24) CRIAMOS AS VIEWS DO RESERVATIONS

# 25) CRIOU O PAGE HOME - COM BANNER, CARD E CAMPO DE PESQUISA DE TRAILER

====================================================

1) Como colocar a Home com o formulario de pesquisa? Qual caminho?
trailer - coordinates
************AULA DE QUINTA VEREMOS O SEARCH*******************

app/views/pages/home.html.erb
<div class="banner">
  <div class="container justify-content-between d-flex">
    <div class='banner-welcome'>
      <h1>Bem-vindos ao <strong>Tem Trailer</strong></h1>
      <p>Venha descobrir os melhores trailers e motorhomes do mercado</p>
      <p>O Marketplace dos Trailers e Motorhomes</p>
      <%= link_to "View all Trailers", trailers_path, class:"btn btn-flat"%>
    </div>
    <div class="card-form p-4 card-border">
      <h1 class="mb-3">Encontre seu trailer:</h1>

      <%= simple_form_for :search, url: trailers_path, method: :get do |f| %>
        <%= f.input :query, label: false, input_html: { placeholder: "Find your trailer", value: nil }%>
        <%= f.input :capacity, as: :select, collection: 1..8 %>
        <%= f.date_field :start_date, min: Date.today, class:"my-3" %>
        <%= f.date_field :end_date, class:"my-3" %>
        <%= f.submit "Search", class:"btn btn-primary" %>
      <% end %>
<%
=begin%>
      <%= form_tag trailers_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control my-2",
          placeholder: "Find your trailer"
        %>
        <%= select_tag :capacity, options_for_select((1..8)),
          class: "form-control my-2",
          placeholder: "Numero de pessoas"
        %>
        <div class="d-flex flex-column my-2">
          <div>
            select_date(date = Date.current, options = {}, html_options = {})
            <p id="date">Start Date</p> <%= date_select("reservation", "start_date") %>
          </div>
          <div>
           <p id="date" class="mt-1">End Date</p> <%= date_select("reservation", "end_date")%>
          </div>
        </div>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
<%
=end%>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container mt-4">
  <% if current_user.photo.attached?  %>
    <%= cl_image_tag current_user.photo.key, class: " avatar-profile mb-3" %>
    <% else %>
  <% end %>
  <h2>Olá, <%= current_user.first_name.capitalize %> </h2>
  <p>Aqui estão as informações do seu perfil, <%= link_to "clique aqui", edit_user_registration_path %> se quiser alterá-las</p>
  <div>
    <div style="display:inline-block mt-4">
      <h4 class="mt-4">Nome:</h4>
      <%= current_user.first_name.capitalize %> <%=  current_user.last_name.capitalize %>
      <h4 class="mt-4">E-mail:</h4>
      <%=  current_user.email %>
      <h4 class="mt-4">Telefone:</h4>
      <%=  current_user.phone_number %>
      <h4 class="mt-4">Informações adicionais:</h4>
      <%=  current_user.description %>
    </div>
  </div>
<div class="container mt-4">
  <h2>Reservas dos seus trailers</h2>
  <% if @reservations_owner.any? %>
    <% @reservations_owner.each do |reservation| %>
    <div class="card p-3">
      <p><%= simple_format reservation.info %></p>
    </div>
    <% end %>
  <% else %>
    <p>Não há reservas</p>
  <% end %>
  <h2>Reservas para suas viagens programadas</h2>
  <% if @reservations_client.any? %>
    <% @reservations_client.each do |reservation| %>
    <div class="card p-3">
      <p><%= simple_format reservation.info %></p>
    </div>
    <% end %>
  <% else %>
    <p>Não há reservas</p>
  <% end %>
</div>
  <%= link_to "Voltar para home", root_path, class:"btn btn-success mt-4" %>
</div>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/show.html.erb
<div class="container mt-4">
  <h1>Sua reserva foi confirmada!</h1>
  <p>Aqui estão os detalhes da reserva:</p>
  <div>
      <h2 class="mt-4"><strong>Data de início: </strong><i> <%= l(@reservation.start_date, format:'%A, %d %b %Y') %> </i> </h2>
      <h2 class="mt-4"><strong>Data de devolução: </strong><i> <%= l(@reservation.end_date, format:'%A, %d %b %Y') %>  </i></h2>
      <h2 class="mt-4"><strong>Trailer reservado:</strong><i> <%= @reservation.trailer.model %></i></h2>
  </div>

  <%= link_to "Voltar para home", root_path, class:"btn btn-success mt-4" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/fematarazzo/tem_trailer"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    Alugue seu trailer e vivencie novas experiências com a Tem Trailer <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    Tem Trailer
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if  !current_user %>
        <li class="nav-item active">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Insert your Trailer", new_trailer_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Manage my Trailers", user_trailers_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My profile", profiles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
          <%= image_tag 'https://mgoblog.com/sites/mgoblog.com/files/Dwight-dwight-schrute-16214468-595-324_thumb.jpg', class: "avatar" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/trailers/_form.html.erb
<div class="container mt-4">
  <%= simple_form_for trailer do |f| %>
    <%= f.input :model %>
    <%= f.input :onboard_capacity %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:"btn btn-primary" %>
  <% end %>
</div>

app/views/trailers/_info_window.html.erb
<% @trailers.each do |trailer| %>
  <h4><%= trailer.model %></h4>
  <p><%= trailer.address %></p>
<% end %>

app/views/trailers/edit.html.erb
<h1>Trailers#edit</h1>
<p>Find me in app/views/trailers/edit.html.erb</p>

<%= render 'form', trailer: @trailer  %>

app/views/trailers/index.html.erb
<div class="container mt-4">

  <h1>Conheça todos os nossos trailers</h1>
  <p>Abaixo nossa seleção de trailers exclusiva para você</p>

  <div class="row">
    <div class="col-7">
      <% # Iteracao sobre cada um dos trailers %>
      <div class="row">
        <% @trailers.each do |trailer| %>
          <% #Crio um card com a largura definida abaixo %>
          <div class="card m-2 card-main card-border col-12 col-lg-5" style="width: 100%">
            <% #card vai ter a image do trailer %>
            <div class="card-image">
              <%= cl_image_tag trailer.photo.key, class:"card-img-top mt-2"%>
            </div>
            <% #corpo com texto do card %>
            <div class="card-body">
              <% #Link clicavel com o modelo do trailer %>
              <%= link_to trailer_path(trailer), class:"card-link card-title" do %>
                <h5 class="card-title"> <%= trailer.model %></h5>
              <% end %>
              <% #descricao pequena do trailer %>
              <p class="card-text"> Descrição: <%= trailer.description %></p>
              <p class="card-text"> $ <%= trailer.price %> a diária </p>
               <p class="card-text"> Capacidade: <%= trailer.onboard_capacity %> pessoas </p>

              <hr>
              <% #botoes dos cards %>

              <div class="d-flex text-right">
                <%= link_to "More info", trailer_path(trailer), class:"card-link" %>
                <% # if trailer.user == current_user || current_user.admin? %>
                  <%= link_to "Edit", edit_trailer_path(trailer), class:"card-link card-edit" %>
                  <%= link_to "Delete", trailer_path(trailer), method: :delete,
                  data: { confirm: "Are you sure?" }, class:"card-link card-delete" %>
                <% # end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-5">
      <div id="map"
         style="width: 100%; height: 600px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/trailers/new.html.erb
<div class="container mt-4">

<h1>Insira seu Trailer</h1>
<p>Quer alugar seu trailer para os outros? Cadastre aqui: </p>

<%= render 'form', trailer: @trailer  %>

</div>

app/views/trailers/show.html.erb
<% content_for :meta_title, "#{@trailer.model} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @trailer.description %>

<div class="container mt-4">

  <h1>Detalhes deste trailer</h1>

  <div class="card">
    <%= cl_image_tag @trailer.photo.key, crop: :pad %>
    <div class="d-flex justify-content-between p-5">
      <div class="card-model p-3 card-border card-width">
        <h1> <%= @trailer.model %> </h1>
        <h4> Description:</h4>
        <h4> <%= @trailer.description %> </h4>
        <hr>
        <div class="d-flex justify-content-left">
          <p> Localidade:</p>
          <p class="ml-2"> <%= @trailer.address %> </p>
        </div>
        <div class="d-flex justify-content-left">
          <p> Onboard Capacity:</p>
          <p class="ml-2"> <%= "#{@trailer.onboard_capacity}" %> </p>
        </div>
      </div>
      <div class="card-model p-3 card-border">
        <h1>Faça sua reserva:</h1>
        <%= simple_form_for [ @trailer, @reservation ] do |f| %>
          <%= f.date_field :start_date, min: Date.today, class:"my-5" %>
          <%= f.date_field :end_date, class:"my-5" %>
          <%= f.button :submit, class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_trailers/index.html.erb
<div class="container mt-4">
  <div class="text-center my-4">
    <h1> Seus Trailers</h1>
    </div>
      <% if @trailers.present? %>
        <% @trailers.each do |trailer| %>
            <div class="card">
              <div class="d-flex justify-content-between align-items-center p-3">
                <div>
                  <h1><%= trailer.model %></h1>
                  <p>  <%= trailer.description %> </p>
                  <%= link_to "Edite seu trailer", edit_trailer_path(trailer), class:"btn btn-success" %>
                </div>
                <div class="card-trailers">
                  <%= cl_image_tag trailer.photo.key, class:"card-img-top mt-2 ml-4"%>
                </div>
              <div>
                 <div class="d-flex align-items-center">
                    <%= link_to "Gerencie as reservas do trailer", user_trailer_path(trailer), class:"btn btn-primary" %>
                  </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h1>Você não tem um trailer cadastrado</h1>
        <%= link_to "Cadastre seu trailer", new_trailer_path, class:"btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/user_trailers/show.html.erb
<div class="container mt-4">

  <h1>Todas as reservas de <%= @trailer.model %> </h1>

  <% @trailer.reservations.each do |reservation| %>

    <div class="card d-flex justify-content-between">
      <div><h2>Cliente:<i> <%= reservation.user.first_name %></i></h2></div>
      <div><h2>Início: <i><%= reservation.start_date.strftime("%Y/%m/%d") %></i></h2></div>
      <div><h2>Término: <i><%= reservation.end_date.strftime("%Y/%m/%d") %></i></h2></div>
      <div><h2>Preço: <i><%= reservation.price %></i></h2></div>
    </div>
  <% end %>

</div>